{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os \n",
    "import zipfile as zf\n",
    "from cryptography.fernet import Fernet as fn\n",
    "import random\n",
    "import string\n",
    "import json\n",
    "import time\n",
    "import copy\n",
    "import shutil"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "error = 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def versionControl(version = \"0.0.2\", source=\"Restore Backup\", software=\"Project Ultra Backup\", author=\"Anjal.P\"):\n",
    "    ver = version\n",
    "    sour = source\n",
    "    software = software\n",
    "    creat = author\n",
    "    return ver, sour, software, creat"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def errorSave(where_to_save, error_report, root_directory):\n",
    "    global error\n",
    "    where_to_save = where_to_save + \"//\"\n",
    "    print(\"look at: \", where_to_save + \"Error Report UB.txt\")\n",
    "    ver_control, software_name, creator, section = versionControl()\n",
    "    date_error = str(time.localtime(time.time()).tm_mday) + \".\" + str(time.localtime(time.time()).tm_mon) + \".\" + str(time.localtime(time.time()).tm_year)\n",
    "    if os.path.exists(where_to_save + \"Error Report UB.txt\")==False:\n",
    "        try:\n",
    "            with open(where_to_save + \"Error Report UB.txt\", 'a') as error_file:\n",
    "                error_file.write(\"--\"*50 + \"\\n\")\n",
    "                error_file.write(\"Errors :\" + \"[\" +str(error) + \"]\" + \"\\n\")\n",
    "                error_file.write(\"On Running Restore: \" + root_directory + \"\\n\")\n",
    "                error_file.write(\"Created On: \" + date_error + \"\\n\")\n",
    "                error_file.write(\"Report: \\n\")\n",
    "                for eachError in error_report:\n",
    "                    error_file.write(\"     > \" + eachError + \" \" + error_report[eachError])\n",
    "                error_file.write(\"This is an automated report generated by \" + str(software_name) + \" \" + str(ver_control) + \" \" + \"Author: \" + str(creator) + \"\\n\")\n",
    "                error_file.write(\"--\"*50 + \"\\n\")\n",
    "                error_file.close()\n",
    "        except Exception as e:\n",
    "            print(\"Error even creating the error log .txt at: \" + where_to_save + \"Error Report UB.txt\")\n",
    "            print(\"Error Report: \" + str(error_report))\n",
    "            print(\"Error on errorSave: \" + str(e))\n",
    "    else:\n",
    "        try:\n",
    "            with open(where_to_save + \"Error Report UB.txt\", 'a') as error_file:\n",
    "                error_file.write(\"--\"*50 + \"\\n\")\n",
    "                error_file.write(\"Errors :\" + \"[\" +str(error) + \"]\" + \"\\n\")\n",
    "                error_file.write(\"On Running Backup: \" + root_directory + \"\\n\")\n",
    "                error_file.write(\"Created On: \" + date_error + \"\\n\")\n",
    "                error_file.write(\"Report: \\n\")\n",
    "                for eachError in error_report:\n",
    "                    error_file.write(\"     > \" + eachError + \" \" + error_report[eachError])\n",
    "                error_file.write(\"This is an automated report generated by \" + str(software_name) + \" \" + str(ver_control) + \" \" + \"Author: \" + str(creator) + \"\\n\")\n",
    "                error_file.write(\"--\"*50 + \"\\n\")\n",
    "                error_file.close()\n",
    "        except:\n",
    "            print(\"Error even creating the error log .txt at: \" + where_to_save + \"Error Report UB.txt\")\n",
    "            print(\"Error Report: \" + str(error_report))\n",
    "            print(\"Error on errorSave: \" + str(e))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def scanBackupDirectory(backupDirectory, ubmapDirectory, toRecover, workingDirectory):\n",
    "    backupScan = {\"UB_date\":{}, \".UBmap\":{}, \".val\":{}}    #    in arangement as : {\"UB_date\": [], \".UBmap\": [], \".val\": []} of selected folder toRecover.\n",
    "    count = 0\n",
    "    for folder, subfolder, files in os.walk(backupDirectory):   #scanning the backup directory of the restor of the toRecover folder backups\n",
    "        if \"oldBackup\" not in folder:\n",
    "            if toRecover==os.path.basename(folder):\n",
    "                for file in files:\n",
    "                    if file[-4:]==\".val\":    #scanned .val and folder name.\n",
    "                        backupScan[\".val\"][count] = folder.replace(\"\\\\\", \"//\") + \"//\" + file\n",
    "                        backupScan[\"UB_date\"][count] = folder.replace(\"\\\\\", \"//\")\n",
    "                        count += 1\n",
    "    for folder, subfolder, files in os.walk(ubmapDirectory):    #reading the ubmap file and arranging accroding to the orede of .val files.\n",
    "        if \"oldUBmap\" not in folder:\n",
    "            for valfiles in backupScan[\".val\"]:\n",
    "                for ubfiles in files:\n",
    "                    if os.path.basename(backupScan[\".val\"][valfiles])[:-3]==ubfiles[:-5]:\n",
    "                        backupScan[\".UBmap\"][valfiles] = folder.replace(\"\\\\\", \"//\") + \"//\" + ubfiles\n",
    "    if len(backupScan[\".val\"])==0:\n",
    "        print(\"Sorry... no backup to restore on: \" + toRecover)\n",
    "    if len(backupScan[\".val\"])!=len(backupScan[\".UBmap\"]):\n",
    "        print(\"It seems that some UBmap files are missing, taking measures for the optimal backups\")\n",
    "    return backupScan"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def scanDate(directoryToScan):\n",
    "    scan = {}\n",
    "    for folder, subfolder, files in os.walk(directoryToScan):\n",
    "        for file in files:\n",
    "            if file[-4:]==\".eUB\" or file[-4:]==\".sUB\":\n",
    "                scan[file] = folder.replace(\"\\\\\", \"//\")\n",
    "    return scan"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "def restore(restoreDirectory, backupDirectory, toRecover, workingDirectory, backupScan):\n",
    "    global error\n",
    "    errorReport = {}\n",
    "    if os.path.isdir(restoreDirectory)==False:\n",
    "        try:\n",
    "            os.makedirs(restoreDirectory)\n",
    "        except Exception as e:\n",
    "            error += 1\n",
    "            errorReport[\"er_create_restoredir\"] = restoreDirectory\n",
    "            errorReport[\"Error: \"] = str(e)\n",
    "            errorReport[\"Plan of action: \"] = \"Please select another directory.\"\n",
    "            errorSave(workingDirectory, errorReport, restoreDirectory)\n",
    "            return\n",
    "    for eachUBFile in backupScan[\".UBmap\"]:\n",
    "        try: \n",
    "            with open(backupScan[\".UBmap\"][eachUBFile], 'r') as ubfile:    #readingt he ubmap file and saving it to a variable ubstore\n",
    "                try:\n",
    "                    ubstore = json.load(ubfile)\n",
    "                    ubfile.close()\n",
    "                except Exception as e:\n",
    "                    ubfile.close()\n",
    "                    error += 1\n",
    "                    errorReport[\"er_load_ubmap\"] = backupScan[\".UBmap\"][eachUBFile]\n",
    "                    errorReport[\"Error: \"] = str(e)\n",
    "                    errorSave(workingDirectory, errorReport, ubmapDirectory)\n",
    "        except Exception as e:\n",
    "            error += 1\n",
    "            errorReport[\"er_open_UBmap\"] = backupScan[\".UBmap\"][eachUBFile]\n",
    "            errorReport[\"Error: \"] = str(e)\n",
    "            errorReport[\"Effect: \"] = \"Some files cannot be backed up due to, not accessible .UBmap or try again\"\n",
    "            errorSave(workingDirectory, errorReport, ubmapDirectory)\n",
    "        scanUBFiles = scanDate(backupScan[\"UB_date\"][eachUBFile])    #scan the eUB and sUB files in the folder.\n",
    "        for eachData in ubstore:             #restoring the files\n",
    "            if os.path.isdir(restoreDirectory + eachData)==False:\n",
    "                try: \n",
    "                    os.makedirs(restoreDirectory + eachData)          #creating the folder.\n",
    "                except Exception as e:\n",
    "                    error += 1\n",
    "                    errorReport[\"er_create_dir\"] = restoreDirectory + eachData\n",
    "                    errorReport[\"Error: \"] = str(e)\n",
    "                    errorReport[\"Plan of action: \"] = \"Please select another directory.\"\n",
    "                    errorSave(workingDirectory, errorReport, restoreDirectory)\n",
    "                    return\n",
    "            for withinData in ubstore[eachData][\"z_n\"]:\n",
    "                if type(ubstore[eachData][\"z_n\"][withinData])==type({}):\n",
    "                    badFile = 0\n",
    "                    randName = ''.join(random.choices(string.ascii_letters + string.digits, k=8))\n",
    "                    for eachSplit in ubstore[eachData][\"z_n\"][withinData]:\n",
    "                        if ubstore[eachData][\"z_n\"][withinData][eachSplit] + \".sUB\" in scanUBFiles:\n",
    "                            try: \n",
    "                                with open(workingDirectory + randName + \".zip\", 'ab') as sUBZipFile:\n",
    "                                    try: \n",
    "                                        with open(scanUBFiles[ubstore[eachData][\"z_n\"][withinData][eachSplit] + \".sUB\"] + \"//\" + ubstore[eachData][\"z_n\"][withinData][eachSplit] + \".sUB\", 'rb') as sUBFile:\n",
    "                                            try: \n",
    "                                                sUBData = sUBFile.read()\n",
    "                                                sUBFile.close()\n",
    "                                            except Exception as e:\n",
    "                                                sUBFile.close()\n",
    "                                                error += 1\n",
    "                                                errorReport[\"er_read_.sUB\"] = scanUBFiles[ubstore[eachData][\"z_n\"][withinData][eachSplit] + \".sUB\"] + \"//\" + ubstore[eachData][\"z_n\"][withinData][eachSplit] + \".sUB\"\n",
    "                                                errorReport[\"Error: \"] = str(e)\n",
    "                                                errorReport[\"Plan of action: \"] = \"Moving to next file to restore.\"\n",
    "                                                errorSave(workingDirectory, errorReport, backupDirectory)\n",
    "                                        decryptKey = (ubstore[eachData][\"k\"][withinData]).encode()\n",
    "                                        decryptKey = fn(decryptKey)\n",
    "                                        try:\n",
    "                                            decryptFile = decryptKey.decrypt(sUBData)\n",
    "                                        except Exception as e:\n",
    "                                            error += 1\n",
    "                                            errorReport[\"er_decrypt_file\"] = scanUBFiles[ubstore[eachData][\"z_n\"][withinData][eachSplit] + \".sUB\"] + \"//\" + ubstore[eachData][\"z_n\"][withinData][eachSplit] + \".sUB\"\n",
    "                                            errorReport[\"Error: \"] = str(e)\n",
    "                                            errorReport[\"Planof action: \"] = \"Looks that the key is not suitable, or the UBmap file is altered....\"\n",
    "                                            errorSave(workingDirectory, errorReport, backupDirectory)\n",
    "                                        try: \n",
    "                                            sUBZipFile.write(decryptFile)\n",
    "                                            sUBZipFile.close()\n",
    "                                        except Exception as e:\n",
    "                                            sUBZipFile.close()\n",
    "                                            error += 1\n",
    "                                            errorReport[\"er_writing_zip\"] = workingDirectory + randName + \".zip\"\n",
    "                                            errorReport[\"Error: \"] = str(e)\n",
    "                                            errorReport[\"Plan of action: \"] = \"Moving to next file.\"\n",
    "                                            errorSave(workingDirectory, errorReport, workingDirectory)\n",
    "                                    except Exception as e:\n",
    "                                        sUBZipFile.close()\n",
    "                                        error += 1\n",
    "                                        errorReport[\"er_open_.sUB\"] = scanUBFiles[ubstore[eachData][\"z_n\"][withinData][eachSplit] + \".sUB\"] + \"//\" + ubstore[eachData][\"z_n\"][withinData][eachSplit] + \".sUB\"\n",
    "                                        errorReport[\"Error: \"] = str(e)\n",
    "                                        errorReport[\"Plan of action: \"] = \"Moving to next file\"\n",
    "                                        errorSave(workingDirectory, errorReport, backupDirectory)\n",
    "                            except Exception as e:\n",
    "                                error += 1\n",
    "                                errorReport[\"er_open/create_zip\"] = workingDirectory + randName + \".zip\"\n",
    "                                errorReport[\"Error: \"] = str(e)\n",
    "                                errorReport[\"Plan of action: \"] = \"Continue with the next files.....\"\n",
    "                                errorSave(workingDirectory, errorReport, workingDirectory)\n",
    "                        else:\n",
    "                            badFile = 1\n",
    "                            print(\"Some files are missing from the backup directory.\")\n",
    "                            print(\"Restore of: \" + ubstore[eachData][\"z_n\"][withinData] + \" is currently not possible...\")\n",
    "                            print(\"Missing file: \" + ubstore[eachData][\"z_n\"][withinData][eachSplit] + \".sUB\")\n",
    "                    if badFile!=1:\n",
    "                        try:\n",
    "                            openZip = zf.ZipFile(workingDirectory + randName + \".zip\")\n",
    "                            try: \n",
    "                                openZip.extractall(restoreDirectory + eachData + \"//\")\n",
    "                                openZip.close()\n",
    "                            except Exception as e:\n",
    "                                openZip.close()\n",
    "                                error += 1\n",
    "                                errorReport[\"er_extracting_files: \"] = workingDirectory + randName + \".zip\"\n",
    "                                errorReport[\"Error: \"] = str(e)\n",
    "                                errorReport[\"Plan of action: \"] = \"Move to next file\" + \" Cause amy be due to corrupted zip.\"\n",
    "                                errorSave(workingDirectory, errorReport, workingDirectory)\n",
    "                        except Exception as e:\n",
    "                            error += 1\n",
    "                            errorReport[\"er_open_zip\"] = workingDirectory + randName + \".zip\"\n",
    "                            errorReport[\"Error: \"] = str(e)\n",
    "                            errorReport[\"Plan of action: \"] = \"Moving to he next file\"\n",
    "                            errorSave(workingDirectory, errorReport, workingDirectory)\n",
    "                        try: \n",
    "                            os.remove(workingDirectory + randName + \".zip\")\n",
    "                        except Exception as e:\n",
    "                            error += 1\n",
    "                            errorReport[\"er_remove_zip\"] = workingDirectory + randName + \".zip\"\n",
    "                            errorReport[\"Error: \"] = str(e)\n",
    "                            errorSave(workingDirectory, errorReport, workingDirectory)\n",
    "                else:\n",
    "                    if ubstore[eachData][\"z_n\"][withinData] + \".eUB\" in scanUBFiles:\n",
    "                        try: \n",
    "                            with open(scanUBFiles[ubstore[eachData][\"z_n\"][withinData] + \".eUB\"] + \"//\" + ubstore[eachData][\"z_n\"][withinData] + \".eUB\", 'rb') as eUBFile:\n",
    "                                try: \n",
    "                                    eUBData = eUBFile.read()\n",
    "                                    eUBFile.close()\n",
    "                                except Exception as e:\n",
    "                                    eUBFile.close()\n",
    "                                    error += 1\n",
    "                                    errorReport[\"er_read_.eUB\"] = scanUBFiles[ubstore[eachData][\"z_n\"][withinData] + \".eUB\"] + \"//\" + ubstore[eachData][\"z_n\"][withinData] + \".eUB\"\n",
    "                                    errorReport[\"Error: \"] = str(e)\n",
    "                                    errorReport[\"Plan of action: \"] = \"Moving to next file\"\n",
    "                                    errorSave(workingDirectory, errorReport, workingDirectory)\n",
    "                        except Exception as e:\n",
    "                            error += 1\n",
    "                            errorReport[\"er_open_.eUB\"] = scanUBFiles[ubstore[eachData][\"z_n\"][withinData] + \".eUB\"] + \"//\" + ubstore[eachData][\"z_n\"][withinData] + \".eUB\"\n",
    "                            errorReport[\"Error: \"] = str(e)\n",
    "                            errorReport[\"Plan of action: \"] = \"Moving to next file\"\n",
    "                            errorSave(workingDirectory, errorReport, workingDirectory)\n",
    "                        decryptKey = (ubstore[eachData][\"k\"][withinData]).encode()\n",
    "                        decryptKey = fn(decryptKey)\n",
    "                        try:\n",
    "                            decryptFile = decryptKey.decrypt(eUBData)\n",
    "                        except Exception as e:\n",
    "                            error += 1\n",
    "                            errorReport[\"er_decrypt_file\"] = scanUBFiles[ubstore[eachData][\"z_n\"][withinData] + \".eUB\"] + \"//\" + ubstore[eachData][\"z_n\"][withinData] + \".eUB\"\n",
    "                            errorReport[\"Error: \"] = str(e)\n",
    "                            errorReport[\"Planof action: \"] = \"Looks that the key is not suitable, or the UBmap file is altered....\"\n",
    "                            errorSave(workingDirectory, errorReport, backupDirectory)\n",
    "                        try: \n",
    "                            with open(workingDirectory + ubstore[eachData][\"z_n\"][withinData] + \".zip\", 'wb') as zipFile:\n",
    "                                try: \n",
    "                                    zipFile.write(decryptFile)\n",
    "                                    zipFile.close()\n",
    "                                except Exception as e:\n",
    "                                    zipFile.close()\n",
    "                                    error += 1\n",
    "                                    errorReport[\"er_writing_zip\"] = workingDirectory + ubstore[eachData][\"z_n\"][withinData] + \".zip\"\n",
    "                                    errorReport[\"Error: \"] = str(e)\n",
    "                                    errorReport[\"Paln of action: \"] = \"Moving to next files.\"\n",
    "                                    errorSave(workingDirectory, errorReport, workingDirectory)\n",
    "                        except Exception as e:\n",
    "                            error += 1\n",
    "                            errorReport[\"er_create_zip\"] = workingDirectory + ubstore[eachData][\"z_n\"][withinData] + \".zip\"\n",
    "                            errorReport[\"Error: \"] = str(e)\n",
    "                            errorReport[\"Paln of action: \"] = \"Moving to next files.\"\n",
    "                            errorSave(workingDirectory, errorReport, workingDirectory)\n",
    "                        try: \n",
    "                            openZip = zf.ZipFile(workingDirectory + ubstore[eachData][\"z_n\"][withinData] + \".zip\")\n",
    "                            openZip.extractall(restoreDirectory + eachData + \"//\")\n",
    "                            openZip.close()\n",
    "                        except Exception as e:\n",
    "                            error += 1\n",
    "                            errorReport[\"er_open_zip\"] = workingDirectory + ubstore[eachData][\"z_n\"][withinData] + \".zip\"\n",
    "                            errorReport[\"Error: \"] =str(e)\n",
    "                            errorReport[\"Plan of action: \"] = \"Not able to open zip due to corruption. Skipping the file.\"\n",
    "                            errorSave(workingDirectory, errorReport, workingDirectory)\n",
    "                        try: \n",
    "                            os.remove(workingDirectory + ubstore[eachData][\"z_n\"][withinData] + \".zip\")\n",
    "                        except Exception as e:\n",
    "                            error += 1\n",
    "                            errorReport[\"er_remove_zip\"] = workingDirectory + ubstore[eachData][\"z_n\"][withinData] + \".zip\"\n",
    "                            errorReport[\"Error: \"] = str(e)\n",
    "                            errorSave(workingDirectory, errorReport, workingDirectory)  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "def restoreBackup(backupDirectory, restoreDirectory, ubmapDirectory, workingDirectory, toRecover):\n",
    "    global error\n",
    "    errorReport = {}\n",
    "    if os.path.isdir(backupDirectory)==False:\n",
    "        error += 1\n",
    "        errorReport[\"dO not exist\"] = \"Backup directory: \" + backupDirectory + \" do not exist.\"\n",
    "        errorSave(workingDirectory, errorReport, backupDirectory)\n",
    "        return\n",
    "    if os.path.isdir(restoreDirectory)==False:\n",
    "        try:\n",
    "            os.makedirs(restoreDirectory)\n",
    "        except Exception as e:\n",
    "            error += 1\n",
    "            errorReport[\"er_crete_folder\"] = restoreDirectory\n",
    "            errorReport[\"Error: \"] = str(e)\n",
    "            errorReport[\"Plan of action: \"] = \"Choose a different folder.\"\n",
    "            errorSave(workingDirectory, errorReport, restoreDirectory)\n",
    "            return\n",
    "    if os.path.isdir(ubmapDirectory)==False:\n",
    "        error += 1\n",
    "        errorReport[\"dO not exist\"] = \"Ubmap Directory: \" + ubmapDirectory + \" do not exist.\"\n",
    "        errorSave(workingDirectory, errorReport, ubmapDirectory)\n",
    "        return\n",
    "    if os.path.isdir(workingDirectory)==False:\n",
    "        try:\n",
    "            os.makedirs(workingDirectory)\n",
    "        except Exception as e:\n",
    "            error += 1\n",
    "            errorReport[\"er_crete_folder\"] = workingDirectory\n",
    "            errorReport[\"Error: \"] = str(e)\n",
    "            errorReport[\"Plan of action: \"] = \"Choose a different folder.\"\n",
    "            errorSave(workingDirectory, errorReport, workingDirectory)\n",
    "            return\n",
    "    try:\n",
    "        backupScan = scanBackupDirectory(backupDirectory + \"//\", ubmapDirectory + \"//\", toRecover, workingDirectory + \"//\")\n",
    "    except Exception as e:\n",
    "        error += 1\n",
    "        errorReport[\"er_backupscan: \"] = str(e)\n",
    "        errorSave(workingDirectory, errorReport, backupDirectory)\n",
    "        print(\"Something went wrong.\")\n",
    "        return\n",
    "    try:\n",
    "        restore(restoreDirectory + \"//\", backupDirectory + \"//\", toRecover, workingDirectory + \"//\", backupScan)\n",
    "    except Exception as e:\n",
    "        error += 1\n",
    "        errorReport[\"er_restore: \"] = str(e)\n",
    "        errorSave(workingDirectory, errorReport, restoreDirectory)\n",
    "        print(\"Something went wrong.\")\n",
    "        return\n",
    "    return \"Success\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
